### ISSUE TITLE
[RFE] Develop API endpoints to send shards of the file to multiple nodes in the network.

### ISSUE THREAD

**Issue by pkesavap** [Prajith007007/Fodgers_DHT#20]
Currently, the flow is:-

When the user selects and uploads a file, the shards are send to to only those nodes where the the request is being served and not to all the nodes in the network.

There is a need to implement API endpoints where when the user uploads a file, the encrypted shards go to  the given list of nodes in the network.(Currently the nodes in the network are given as input or hardcoded, opening a separate issue to find the nodes in a network)

**Comment by tewarig** [comment]
I would like to work on this issue

**Comment by pkesavap** [comment]
@tewarig Done.

Please make sure to reference this issue in your PR.

As discussed I will create a separate issue for finding the registered nodes in the network

**Comment by tewarig** [comment]
sure
