### ISSUE TITLE
Update homepage with  interactive particle elements 

### ISSUE THREAD

**Issue by pkesavap** [Prajith007007/Fodgers_DHT#31]
The homepage of the web application could use an interactive and responsive page, with particle.js, thus improving UX.

**Comment by pkesavap** [comment]
@tewarig as discussed, we can proceed with the the intended design, and implement the homepage.

I will create another issue for Register/Sign in flow.

**Comment by tewarig** [comment]
I did tried to find out many ways to add multiple images in particlesjs but looks like it does no supports it. https://github.com/VincentGarreau/particles.js/issues/106  we might create multiple instances of it.
but it will slow down the site. https://github.com/VincentGarreau/particles.js/issues/324

I suggest we can use tsParticles it supports multiple images. 
https://dev.to/matteobruni/5-reasons-to-use-tsparticles-and-not-particles-js-1gbe

**Comment by pkesavap** [comment]
@tewarig Understood, Lets go with partilce.Ts

**Comment by tewarig** [comment]
So I was able to add multiple images in particle js, here is  a demo of that
https://user-images.githubusercontent.com/54894783/118525494-deeed380-b75c-11eb-8ef0-2ad05a619400.mp4 
you can check live deployment here.   http://forgedht-ui.vercel.app/

**Comment by pkesavap** [comment]
Great Start !! 

A couple of points

1) Could we figure out a way to not repeat the photos. For example, if I hover over a connected cluster, and I have 5 images parsed, it can show only 5 and does not need to repeat it for every point
2) Could we also, leave space between nodes, so that two photos do not overlap each other
3) Instead of a square, if the photos were in a circle, that would look good.

**Comment by matteobruni** [comment]
> Great Start !!
> 
> A couple of points
> 
> 1. Could we figure out a way to not repeat the photos. For example, if I hover over a connected cluster, and I have 5 images parsed, it can show only 5 and does not need to repeat it for every point
> 2. Could we also, leave space between nodes, so that two photos do not overlap each other
> 3. Instead of a square, if the photos were in a circle, that would look good.

Hello, I found this thread on GitHub and I’d like to help you with these questions.

All the points above can be seen here https://codepen.io/matteobruni/pen/BaomBYv

Collisions prevent overlapping, duplicate reduction prevents random generation (if you use 10 images and 10 particles, you will have all different particles) and all particles are treated like circles since the difference is minimal. If you use a transparent image, you can shape them as you prefer

**Comment by tewarig** [comment]
> > Great Start !!
> > A couple of points
> > 
> > 1. Could we figure out a way to not repeat the photos. For example, if I hover over a connected cluster, and I have 5 images parsed, it can show only 5 and does not need to repeat it for every point
> > 2. Could we also, leave space between nodes, so that two photos do not overlap each other
> > 3. Instead of a square, if the photos were in a circle, that would look good.
> 
> Hello, I found this thread on GitHub and I’d like to help you with these questions.
> 
> All the points above can be seen here https://codepen.io/matteobruni/pen/BaomBYv
> 
> Collisions prevent overlapping, duplicate reduction prevents random generation (if you use 10 images and 10 particles, you will have all different particles) and all particles are treated like circles since the difference is minimal. If you use a transparent image, you can shape them as you prefer

hey, @matteobruni  thank you so much.  this would help a lot.

**Comment by tewarig** [comment]
hi, @pkesavap so I was able to create this using tsparticle.js
![Screenshot from 2021-05-19 19-37-02](https://user-images.githubusercontent.com/54894783/118827580-2353ae00-b8da-11eb-8c0c-80e02b76ccc9.png)
![Screenshot from 2021-05-19 19-37-05](https://user-images.githubusercontent.com/54894783/118827599-277fcb80-b8da-11eb-8af7-f02e14054a95.png)
https://forgedht-ui.vercel.app/

**Comment by pkesavap** [comment]
@tewarig looks solid,

few points more :-
1) can we centralize the project name in the middle and have the cluster nodes around the oval width of it.
2) Could we increase the width of the nodes
3) maybe we could add more pictures and particles and still maintain non-repetition of the pictures until that picture is out of the page. 
4) Re-iterating pioint 1, Lets make sure to have nodes surround the project name, . Maybe we can have specific set of nodes which just go here and there, and hovering could show the pictures, and remove increasing of nodes while clicking , thus limiting that interaction. What do you think?

**Comment by tewarig** [comment]
http://forgedht-ui.vercel.app/ 
here is an update on the home page part. 
now the images are non-repeating, they also have an animation, they move around the screen above the particle section. also, the number of nodes has been increased. 
![Screenshot from 2021-05-24 21-43-04](https://user-images.githubusercontent.com/54894783/119376257-5c748f80-bcd9-11eb-93bb-5293bcc79507.png)

**Comment by pkesavap** [comment]
Looks solid, you can open a PR for this and link it to this issue.

**Comment by tewarig** [comment]
hi, as we discuss the home page, I created a new UI from scratch.. here is a new UI 
https://forgedht-ui.vercel.app/new/index.html
![Screenshot from 2021-06-27 17-13-29](https://user-images.githubusercontent.com/54894783/123543414-e8138d00-d76b-11eb-85eb-86ac447f1fcc.png)
