### ISSUE TITLE
Upload feature 

### ISSUE THREAD

**Issue by pkesavap** [Prajith007007/Fodgers_DHT#33]
Implement a system where the users can upload images from the UI.

Currently, images are being parsed from the cli. We require a UI with upload functionality that retains the previous and the current images in the platform.

**Comment by tewarig** [comment]
So, here is the update regarding the Upload image UI. this what the new UI looks like.
it has : -  

- [ ] sidebar for navigation (animated)
- [ ] separate upload button 
- [ ] own image gallery (responsive)
- [ ] click to zoom feature (single click to zoom in and zoom out)

![Screenshot from 2021-05-26 22-21-23](https://user-images.githubusercontent.com/54894783/119700422-d1c69880-be70-11eb-8f35-1ea8647978f2.png)
you can check the live preview of it here.
https://forgedht-ui.vercel.app/upload/index.html

**Comment by pkesavap** [comment]
@tewarig good start :)

I noticed a couple of things here:-

1) The images are static one, i think a good approach would be to create a new cards.html dedicated for each photos and then in the main html file reference the cards.html for each image, that way i think we could make the images more responsive, like on hover or onClick.
2) The side navbar while opening is not making the images reorder to accomodate the screen
3)Create a nav bar on top as well, with logo, search and upload button
4) Maybe you could resue the code for existing upload functionality in the project and implement them here.
5) With respect to point 1, it would also be good if we could go to have a next and previous button to seamlessly go through the list of photos.

**Comment by tewarig** [comment]
Here is update regarding the new UI.

https://forgedht-ui.vercel.app/upload/index.html

- [ ]  I have added a new nav bar on the top
- [ ]  Image gallery has been updated from scratch. now it has a hover feature and next, previous,  close buttons as well. 

![Screenshot from 2021-05-28 13-29-11](https://user-images.githubusercontent.com/54894783/119952018-317c8b00-bfba-11eb-8e24-29faa5c234fc.png)

![Screenshot from 2021-05-28 13-29-23](https://user-images.githubusercontent.com/54894783/119951969-26295f80-bfba-11eb-95d8-b0599f491634.png)

**Comment by pkesavap** [comment]
@tewarig  Way better looking now :) 

Just one more point
1) Going to left side navbar the images are not being auto segregated as i mentioned
2) Good Job implementing the next, previous, and the opening (pop up of image)
   can we enlarge the popup in a way where the background becomes black and the image gets a standard size, rather than it changing for each photos (This is a good to have feature --> so if implementing this takes time we can park it and work on the others and create a issue to track this in the future)
  
  3) Just make sure to implement point 1 though and you can open a PR for this adaptive to python flask framework, thus make sure to reuse the existing code to implement upload functionality :)

**Comment by tewarig** [comment]
@pkesavap I have implemented image adaptiveness now as well. 
check this:-
https://forgedht-ui.vercel.app/upload/index.html

https://user-images.githubusercontent.com/54894783/120014371-9a3a2680-bfff-11eb-9d40-3552b75ca3d7.mp4

**Comment by pkesavap** [comment]
@tewarig let's raise a PR to attach it to the main project.
BTW, good job :)

**Comment by tewarig** [comment]
Hi, @pkesavap maybe you can close this
