### ISSUE TITLE
Implement a new UI for signup/sign in

### ISSUE THREAD

**Issue by pkesavap** [Prajith007007/Fodgers_DHT#34]
Implement a UI for signup/signin procedure.

few points to remember:-
1) Username field should be autofilled with string before "@" of the email.
2) include a front for forgot password.

**Comment by tewarig** [comment]
So, @pkesavap  here is the task update... the signup and sign-in pages are almost ready. 
Sign up :- https://tewarig.github.io/forgedht-ui/signup/index.html
Sign In :- https://tewarig.github.io/forgedht-ui/signin/index.html
please have a look.
![Screenshot from 2021-05-31 23-00-33](https://user-images.githubusercontent.com/54894783/120226891-c1922d00-c265-11eb-9335-36707a6dfd58.png)
![Screenshot from 2021-05-31 23-01-07](https://user-images.githubusercontent.com/54894783/120226902-c5be4a80-c265-11eb-8a61-ff4b1ffcf7b1.png)

**Comment by pkesavap** [comment]
Looks good,

1) Could we reduce the length of each field
2) Could we leave gaps between each field
3) I hope point 1 & 2 makes the entire login/sign-in card (black color rectangle containing the fields) become proper rectange in proportion with the screen

**Comment by pkesavap** [comment]
@tewarig ^^

**Comment by tewarig** [comment]
so , i have updated it.
![Screenshot from 2021-06-01 21-48-10](https://user-images.githubusercontent.com/54894783/120357617-442cf200-c323-11eb-8962-318fd977788f.png)
![Screenshot from 2021-06-01 21-45-59](https://user-images.githubusercontent.com/54894783/120357693-5a3ab280-c323-11eb-9f71-281a3d52aaee.png)

**Comment by pkesavap** [comment]
Right, this seems stable enough, lets proceed with the PR for including it in the project

For the signin/signup the logic exist, so make sure that you leverage the existing back end code, with this front-end.

**Comment by tewarig** [comment]
sure : ) I will make a pr soon.

**Comment by tewarig** [comment]
hi, this issue is solve @pkesavap you can close this : )

**Comment by pkesavap** [comment]
Good job
